# Generated by Django 5.0.6 on 2024-12-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directorsdetails',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
            ],
            options={
                'db_table': 'directorsdetails',
            },
        ),
        migrations.CreateModel(
            name='Genredetails',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
            ],
            options={
                'db_table': 'genredetails',
            },
        ),
        migrations.CreateModel(
            name='Moviecastdetails',
            fields=[
                ('celebrity_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
            ],
            options={
                'db_table': 'moviecastdetails',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=4096, null=True)),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('certificate', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Moviecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.moviecastdetails')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.movies')),
            ],
            options={
                'db_table': 'moviecast',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.genredetails')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.movies')),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.directorsdetails')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.movies')),
            ],
            options={
                'db_table': 'directors',
            },
        ),
    ]