# Generated by Django 5.0.6 on 2024-12-02 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.TextField(unique=True)),
                ('password_hash', models.BinaryField()),
                ('salt', models.BinaryField()),
                ('display_name', models.TextField()),
                ('user_role', models.CharField(default='user')),
                ('email', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Favouritemovies',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie_app.movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favouritemovies',
            },
        ),
    ]