# Generated by Django 5.0.6 on 2024-11-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_favouritemovies_options_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritemovies',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
